### ISSUE TITLE
Checking on EET compatibility

### ISSUE THREAD

**Issue by PixelsnPolygons** [Endarire/The-Undying-Mod-for-BG2EE-EET#1]
Hello Endarire,

I am putting together a ridiculously huge EET installation together, essentially every quest, NPC, item, spell, and kit mod plus a healthy dose of tweaks and tactics mods.

I wanted to include CoM_Solaufein's Undying mod into my installation, but there was some uncertainty with its EET compatibility. What has your experience been with Undying in an EET environment?

Here is my Project Infinity installation sequence so far, but I am still trying to perfect it. Do you have an installation sequence or WeiDU log for a epic EET installation you could share?
[P&P'sPreposterousEETInstallSequence.csv](https://github.com/user-attachments/files/15921642/P.P.sPreposterousEETInstallSequence.csv)

**Comment by Endarire** [comment]
To my present understanding, The Undying mod version I include on this repository has been updated with the EET auto converter (meaning EET compatibility) and the Big World Fix Pack fixes.  As of this writing, it doesn't try to fix any bugs or expand the scope beyond this.

As for other matters, let's talk more on Discord about this since that's easier for me to handle.  My Discord ID is Endarire.

Thankee!

**Comment by PixelsnPolygons** [comment]
Thanks for the update! I sent you a Discord request.

**Comment by Endarire** [comment]
What is your Discord ID?
